/*#include<iostream>
using namespace std;
int main (){
    cout << "Hello This is Manish Here" << endl;
    cout<< "Learning C++ in his sem of  college "<< endl;
    return 0;
}
    */
   #include<iostream>
    using namespace std;
    

    int main (){
         cout << "Hello This is Manish Here" <<endl << "Learning C++ in his sem of  college "; 
         /* so  here we have done the above code in single go we can use this operator 
         << after endl and write the whole paragraph in a single go and then at end we will use the ; and close the get 
         the desired output*/
    }